require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlertsController do

  # This should return the minimal set of attributes required to create a valid
  # Blert. As you add validations to Blert, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlertsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all blerts as @blerts" do
      blert = Blert.create! valid_attributes
      get :index, {}, valid_session
      assigns(:blerts).should eq([blert])
    end
  end

  describe "GET show" do
    it "assigns the requested blert as @blert" do
      blert = Blert.create! valid_attributes
      get :show, {:id => blert.to_param}, valid_session
      assigns(:blert).should eq(blert)
    end
  end

  describe "GET new" do
    it "assigns a new blert as @blert" do
      get :new, {}, valid_session
      assigns(:blert).should be_a_new(Blert)
    end
  end

  describe "GET edit" do
    it "assigns the requested blert as @blert" do
      blert = Blert.create! valid_attributes
      get :edit, {:id => blert.to_param}, valid_session
      assigns(:blert).should eq(blert)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Blert" do
        expect {
          post :create, {:blert => valid_attributes}, valid_session
        }.to change(Blert, :count).by(1)
      end

      it "assigns a newly created blert as @blert" do
        post :create, {:blert => valid_attributes}, valid_session
        assigns(:blert).should be_a(Blert)
        assigns(:blert).should be_persisted
      end

      it "redirects to the created blert" do
        post :create, {:blert => valid_attributes}, valid_session
        response.should redirect_to(Blert.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved blert as @blert" do
        # Trigger the behavior that occurs when invalid params are submitted
        Blert.any_instance.stub(:save).and_return(false)
        post :create, {:blert => {}}, valid_session
        assigns(:blert).should be_a_new(Blert)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Blert.any_instance.stub(:save).and_return(false)
        post :create, {:blert => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested blert" do
        blert = Blert.create! valid_attributes
        # Assuming there are no other blerts in the database, this
        # specifies that the Blert created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Blert.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => blert.to_param, :blert => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested blert as @blert" do
        blert = Blert.create! valid_attributes
        put :update, {:id => blert.to_param, :blert => valid_attributes}, valid_session
        assigns(:blert).should eq(blert)
      end

      it "redirects to the blert" do
        blert = Blert.create! valid_attributes
        put :update, {:id => blert.to_param, :blert => valid_attributes}, valid_session
        response.should redirect_to(blert)
      end
    end

    describe "with invalid params" do
      it "assigns the blert as @blert" do
        blert = Blert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Blert.any_instance.stub(:save).and_return(false)
        put :update, {:id => blert.to_param, :blert => {}}, valid_session
        assigns(:blert).should eq(blert)
      end

      it "re-renders the 'edit' template" do
        blert = Blert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Blert.any_instance.stub(:save).and_return(false)
        put :update, {:id => blert.to_param, :blert => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested blert" do
      blert = Blert.create! valid_attributes
      expect {
        delete :destroy, {:id => blert.to_param}, valid_session
      }.to change(Blert, :count).by(-1)
    end

    it "redirects to the blerts list" do
      blert = Blert.create! valid_attributes
      delete :destroy, {:id => blert.to_param}, valid_session
      response.should redirect_to(blerts_url)
    end
  end

end
